presets:
- labels:
    preset-azure-secrets-store-creds: "true"
  env:
  - name: AZURE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: azure-secrets-store-cred
        key: clientid
  - name: AZURE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: azure-secrets-store-cred
        key: clientsecret
  - name: RESOURCE_GROUP
    valueFrom:
      secretKeyRef:
        name: azure-secrets-store-cred
        key: resourcegroup
  - name: SUBSCRIPTION_ID
    valueFrom:
      secretKeyRef:
        name: azure-secrets-store-cred
        key: subscriptionid
  - name: TENANT_ID
    valueFrom:
      secretKeyRef:
        name: azure-secrets-store-cred
        key: tenantid
